spring:
  application:
    name: sendingEmail
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls: true